### ISSUE TITLE
Team Death Match Ending on Start of Game

### ISSUE THREAD

**Issue by jonmalave** [suriyun-production/battle-io-docs#11]
It seems when you start a new team death match game everything works perfectly fine now since the last update. Although I notice if you exit a team death match before the game ends, and you return and start a new team death match the previous game score remains in memory. 

We need to clear this out, so on exit of Team Death Match the client removes any team scores in memory before starting a new Team Death Match room. 

Please see screenshots below for reference. In the first screenshot I set the Max Kills to 40, then on the second I set the Max Kills to 20, since the previous team scores past 20 already the game automatically ends on start.

![error_01](https://user-images.githubusercontent.com/3487527/79770175-0d507400-82fb-11ea-8aa1-a8b40c6c95b6.jpg)

![error_02](https://user-images.githubusercontent.com/3487527/79770181-10e3fb00-82fb-11ea-868b-b2bf3d365293.jpg)

**Comment by jonmalave** [comment]
Hi @insthync any update on this issue?

**Comment by insthync** [comment]
It might be because of Photon's bugs (That I've reported them https://forum.photonengine.com/discussion/comment/50506)

Not sure the update has been published or not, if not you may try import this package 
[Photon_FixTeamsManagerNullReferences.zip](https://github.com/suriyun-production/battle-io-docs/files/4555102/Photon_FixTeamsManagerNullReferences.zip)

**Comment by jonmalave** [comment]
> It might be because of Photon's bugs (That I've reported them https://forum.photonengine.com/discussion/comment/50506)
> 
> Not sure the update has been published or not, if not you may try import this package
> [Photon_FixTeamsManagerNullReferences.zip](https://github.com/suriyun-production/battle-io-docs/files/4555102/Photon_FixTeamsManagerNullReferences.zip)

Thanks so much for the reply! I will try this soon and report back.

**Comment by Vauxvogh** [comment]
hmm no that didn't seem to fix it Suriyun. It might be because of this errors I was getting when just a regular death match ended. These errors below happens after every regular deathmatch, though it doesn't affect deathmatch at all.

https://i.gyazo.com/bf236b6627e28a90a9831450ec1c5002.png

https://i.gyazo.com/6cd9a4d5547bff35375c4352488f093a.png

**Comment by jonmalave** [comment]
> hmm no that didn't seem to fix it Suriyun. It might be because of this errors I was getting when just a regular death match ended. These errors below happens after every regular deathmatch, though it doesn't affect deathmatch at all.
> 
> https://i.gyazo.com/bf236b6627e28a90a9831450ec1c5002.png
> 
> https://i.gyazo.com/6cd9a4d5547bff35375c4352488f093a.png

Hey @Vauxvogh are you seeing the same problem on your end even after applying the above fix @insthync provided? I haven't had chance to test this yet...

**Comment by Vauxvogh** [comment]
Hey! Yeah unfortunately even after applying the above fix it didn't work.

**Comment by insthync** [comment]
As I try, the error occuring when team death match end but it won't affect gameplay, right?

The codes that cause error is Photon's codes, I actually can avoid it and error messages by just add null check at top of ClearTeams function

**PhotonTeamsManager.cs**
```
        private void ClearTeams()
        {
            if (playersPerTeam == null)
                return;
            foreach (var key in playersPerTeam.Keys)
            {
                playersPerTeam[key].Clear();
            }
        }
```

**Comment by Vauxvogh** [comment]
Hey Suriyun, yes it does affect gameplay for Team Deathmatch. After you play 1 match of Team Death match it doesn't clear the data from that match, so if you go to play another match of Team death match the End game panel will automatically show saying the match is over because a player already won (from the last time you played a team deathmatch)

But regular deathmatch and I.O mode don't seem to be affected nor battle royale. Only team Death match. However those errors I showed above to do appear (after) I play a regular deathmatch or I.O mode. But don't affect those modes, only team deathmatch. :)

**Comment by insthync** [comment]
Ahhh, I see, I will fix it, I might upload the new package within 3 hrs.

**Comment by Vauxvogh** [comment]
Ok sounds great Thanks Suriyun! 
Hey could you check Status Effects that apply damage over time? So if I have a damage entity that applies a status effect and it takes health away from the target over time and they die, it doesn't give me the kill or score, they just die. Was this on purpose or its still supposed to count as a kill right if the status effect kills them?

**Comment by insthync** [comment]
Okay, I will fix it

**Comment by Vauxvogh** [comment]
ok thanks man! we appreciate you!

**Comment by jonmalave** [comment]
@insthync what is the fix for this?

**Comment by insthync** [comment]
Fix kill count/score not reset when start new game.

**Comment by jonmalave** [comment]
> Fix kill count/score not reset when start new game.

you pushed the fix in the latest release you mean?

**Comment by insthync** [comment]
Yes, I mean I've pushed it in latest release
