### ISSUE TITLE
Dedicated Server Option Not Workings with PUN2 Edition

### ISSUE THREAD

**Issue by jonmalave** [suriyun-production/battle-io-docs#15]
Hi @insthync how can we setup a dedicated server with PUN2? 

Yes, i'm aware it would just be a Dedicated Master Client... but that's exactly what I'd like to test out if you don't mind updating the documentation here: https://suriyun-production.github.io/battle-io-docs/#/ on how to achieve this? 

I notice when I create a game I have the option to create a game that appears to be a dedicated server option, but how do we set this up in Unity Headless Server Mode?

**Comment by insthync** [comment]
The PUN2 version has no dedicated server option because it uses PUN2, its networking architecture is different from the UNET version. When we use Photon to create room it will create the room at Photon's cloud server with its [load balancing system](https://doc.photonengine.com/en-US/server/current/applications/loadbalancing/application) to sync networking messages together to all clients. But when we use UNET we have to run the game-server by ourselves to lets players connect.

**Comment by jonmalave** [comment]
@insthync OK understandable... but I guess it would be good for you to update the document with this information because it's not reflecting the PUN2 version of Battle.io
