### ISSUE TITLE
Still Seems to be a good bit of lag

### ISSUE THREAD

**Issue by Vauxvogh** [suriyun-production/battle-io-docs#45]
Hey so the attack animations are lagged on other clients sometimes causing damage entities to be lagged sometimes. Also sometimes if a damage entity hits it doesn't cause damage, or the damage is lagged.

Also sometimes when attacking or using a skill, the player will attack twice or use the skill twice on another players client, when the player only attacked once or used skill once on there client.

Is there a better way you can synchronize all of this? animations and damage entities. Its just doesn't seem to working that well with real players 

what about smooth sync?

**Comment by insthync** [comment]
What if I changed it to not validate attacks at the master client? all other clients will be able to spawn damage entity and also applying damage by themselves, so all clients can hack the game easier. smooth sync won't be useful for this case, it was made to move character entity smoothly and reduce data size. But the attacking can be slow because it has to send data to the master client to validate before the master client send an action message to other clients.

**Comment by Vauxvogh** [comment]
Ah I see. Yeah you're probably right probably best to let is check through master client. Which I'm fine with, but we gotta fix the problem of double attacks being played and double skills being used sometimes on other players clients when the original player only attacks once and uses a skill once. We also need to fix somehow damage entity not damaging the player sometimes when its a direct hit. I tested these on a fresh project of battle.io 126c and it has the same problem.

But what about player movement animation. I'm getting good movement sync, like there's not much jitter they aren't hopping around but its pretty smooth movement, However the actual movement animation doesn't seem to sync that well. It keeps stopping and going (like the animation wont play all the way through and just resets over and over) How can you sync the actual movement animations better?
