### ISSUE TITLE
Photon errors

### ISSUE THREAD

**Issue by nvrkr** [suriyun-production/battle-io-docs#7]
I imported this asset and photon too. After that settings for iap and ads are checked out like  in documents. But  there are too many errors (235). Most of them  is about photon.
What should i do?  Can you help me about this. My unity version is 2019.2.8.f1

**Comment by insthync** [comment]
Please attach screenshot of an error, I can't guess what is happening :P

**Comment by nvrkr** [comment]
Hi. I will post an answer on github. thanks

Ittipon Teerapruettikulchai <notifications@github.com>, 13 Mar 2020 Cum,
11:20 tarihinde şunu yazdı:

**Comment by nvrkr** [comment]
Hİ. I downgrade the unity to 2018.2.8f1 and total error reduced to 5. Attached a screenshot of console. 
![hatalar](https://user-images.githubusercontent.com/62132693/76618080-bb1c7600-6538-11ea-9391-c46f0afd1a2f.PNG)

**Comment by insthync** [comment]
You should not downgrade from 2019.2 to 2018.2 it can break your project, because Unity's prefab system were changes. If you create new project then re-import the package it would fine.

About an error, I am doubting why it can't find  `SceneNameField`.
So please find `SceneNameField` then capture screenshot of the result and attach here.

![Screenshot_60](https://user-images.githubusercontent.com/2697550/76618804-072ce200-655c-11ea-81d9-95bd0d479a79.png)

**Comment by nvrkr** [comment]
Ok. I create a new project in 2018.2 and then import the package. I will post the screenshot finally. thanks

**Comment by nvrkr** [comment]
Hi. I did what you said and here the screenshot 
![Ekran Alıntısı](https://user-images.githubusercontent.com/62132693/76627890-ec9f3c80-654c-11ea-914c-3990cad11d7f.PNG)

**Comment by nvrkr** [comment]
Hi. I did what you said and here the screenshot
![Ekran Alıntısı](https://user-images.githubusercontent.com/62132693/76628114-515a9700-654d-11ea-97d7-079d6a68bfdf.PNG)

**Comment by insthync** [comment]
Try import PUN2 package
